name: Build sysext
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/hello_world
        name: Test Docker action
        with:
          who: "Lola"
